import Badge, { type BadgeTone } from '../ui/Badge';
import type {
  InvoiceItemType,
  InvoicePaymentStatus,
  InvoiceStatus,
  PaymentRecordStatus,
  PaymentType,
} from '../../types';

const INVOICE: Record<InvoiceStatus, { label: string; tone: BadgeTone }> = {
  draft: { label: 'Draft', tone: 'slate' },
  issued: { label: 'Issued', tone: 'blue' },
  cancelled: { label: 'Cancelled', tone: 'red' },
};

export function InvoiceStatusBadge({ status }: { status: InvoiceStatus }) {
  const { label, tone } = INVOICE[status];
  return <Badge tone={tone}>{label}</Badge>;
}

const PAYMENT: Record<InvoicePaymentStatus, { label: string; tone: BadgeTone }> = {
  unpaid: { label: 'Unpaid', tone: 'amber' },
  partially_paid: { label: 'Partially paid', tone: 'blue' },
  paid: { label: 'Paid', tone: 'green' },
  refunded: { label: 'Refunded', tone: 'red' },
};

export function InvoicePaymentBadge({ status }: { status: InvoicePaymentStatus }) {
  const { label, tone } = PAYMENT[status];
  return <Badge tone={tone}>{label}</Badge>;
}

const RECORD: Record<PaymentRecordStatus, { label: string; tone: BadgeTone }> = {
  completed: { label: 'Completed', tone: 'green' },
  failed: { label: 'Failed', tone: 'red' },
  refunded: { label: 'Refunded', tone: 'amber' },
};

export function PaymentRecordBadge({ status, type }: { status: PaymentRecordStatus; type: PaymentType }) {
  if (type === 'refund') return <Badge tone="red">Refund</Badge>;
  const { label, tone } = RECORD[status];
  return <Badge tone={tone}>{label}</Badge>;
}

/**
 * Where a line on an invoice came from. Four sources, four tones — the item
 * type is the one thing that tells a reader whether a charge was generated by
 * the hospital's own records or typed in by hand at the desk.
 */
const ITEM_TYPE: Record<InvoiceItemType, { label: string; tone: BadgeTone }> = {
  consultation: { label: 'Consultation', tone: 'brand' },
  lab_order: { label: 'Laboratory', tone: 'violet' },
  pharmacy: { label: 'Pharmacy', tone: 'teal' },
  service: { label: 'Service', tone: 'slate' },
};

export const itemTypeLabel = (type: InvoiceItemType): string =>
  ITEM_TYPE[type]?.label ?? type.replace('_', ' ');

export function InvoiceItemTypeBadge({ type }: { type: InvoiceItemType }) {
  const spec = ITEM_TYPE[type];
  if (!spec) return <Badge>{itemTypeLabel(type)}</Badge>;
  return <Badge tone={spec.tone}>{spec.label}</Badge>;
}

export const methodLabel = (method: string): string =>
  method.replace('_', ' ').replace(/\b\w/g, (c) => c.toUpperCase());
